### PR TITLE
Remove unused scrutinizer config

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by wiese** [comment]
Just to get this straight. For once we publish a repo that may actually be of use to others and remove QA tools - a well established way to asses state of a 3rd party lib before use - to save us a flick of a switch?

**Comment by JeroenDeDauw** [comment]
This thing has 5 lines of code. You don't need a static analysis tool to help you understand its quality.

**Comment by JeroenDeDauw** [comment]
I've added the thing now https://scrutinizer-ci.com/g/wmde/FreezableValueObject/ even though I think it's utterly useless

**Comment by wiese** [comment]
Thank you, @JeroenDeDauw. Added #2.

**Pull request closed without merging**
